### ISSUE TITLE
Add copyrights/license information

### ISSUE THREAD

**Issue by vazhnov** [terorie/netdata-influx#1]
Hello!
Could you add information about copyrights/license, please?
It would be great to see any popular open source license.

**Comment by riptl** [comment]
Hey, thanks for checking out my tool. I added the MIT License in https://github.com/terorie/netdata-influx/commit/45cf9f8241f2738f19b53a7cdd6fe39783841231, does that work for you?

**Comment by vazhnov** [comment]
@terorie, yes, thank you very much!
