### ISSUE TITLE
Do I need to use “curl -XPOST” instead of “curl -G” ?

### ISSUE THREAD

**Issue by ju0594** [terorie/netdata-influx#2]
~# curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE netdata"

{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE DATABASE netdata' in a read only context, please use a POST request instead"}]}]}

~# curl -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE netdata"

{"results":[{"statement_id":0}]}

**Comment by riptl** [comment]
Correct, thanks for the heads up. I updated the README.
