### ISSUE TITLE
InfluxDB 2.0?

### ISSUE THREAD

**Issue by k8ieone** [terorie/netdata-influx#23]
Hi,
Do you plan on adding support for InfluxDB 2.0? Or is it already supported?

**Comment by riptl** [comment]
Hi @satcom886, InfluxDB 2.0 is supported. Let me know if you think otherwise.

**Comment by k8ieone** [comment]
That's awesome! I just wanted to ask before I spend time on setting this up.

**Comment by riptl** [comment]
@satcom886 BTW this repo is fairly outdated. You can find the most recent method to export Netdata metrics to InfluxDB on Netdata's manual: https://learn.netdata.cloud/docs/export/external-databases
You would instruct Netdata to write to InfluxDB either via Prometheus remote write API or the Graphite interface.

**Comment by k8ieone** [comment]
Actually, that's what I wanted to do first, but I can't seem to find any way to enable Prometheus remote write or Graphite in Influx's docs (at least not in the 2.0 docs). 
Is it already enabled by default?
If so, where should I point Netdata's Prometheus Remote write to?

I assumed Influx completely dropped this functionality in 2.0.

**Comment by riptl** [comment]
@satcom886 Oh you're right. With Influx 2.0, you need to run Telegraf for the Prometheus remote write / Graphite integrations: https://github.com/influxdata/telegraf
Which is kind of annoying. So I'm glad this project might still have some use :)

**Comment by k8ieone** [comment]
@terorie well that's kinda stupid. But I'm sure there's a reason for not having these features in anymore.

**Comment by k8ieone** [comment]
Anyways, thanks for your help!
