### ISSUE TITLE
[Question] How to deploy without Docker?

### ISSUE THREAD

**Issue by MaurUppi** [terorie/netdata-influx#9]
Hi Terorie

I have a OpenWRT w/Netdata running well and a Ubuntu VM w/Grafana, InfluxDB 1.8.x running well also. 
I'm interesting to leverage your amazing dashboard but the question is i don't want to install a docker in Ubuntu VM. 
therefore, there is any way to push netdata from OpenWRT to Ubuntu VM influxDB. OR get data from OpenWRT on Ubuntu side. 
thanks!!

**Comment by riptl** [comment]
@OUZYcn Hey, that's completely understandable. `netdata-influx` does not depend on Docker. You can also run netdata-influx in systemd or via shell.

You can compile this using a Go toolchain, and install it to `/usr/local/bin`.
```
~/opt/netdata-influx $ go mod download
...
~/opt/netdata-influx $ go build -o netdata-influx-build
...
~/opt/netdata-influx $ sudo mv ./netdata-influx-build /usr/local/bin/netdata-influx
```

**Run from shell:**

```shell script
export NI_INFLUX_ADDR=http://influxdb:8086
export NI_INFLUX_DB=netdata
export NI_NETDATA_API=https://netdata:19999/api
export NI_HOST_TAG=localhost-main
export NI_CHARTS=system.cpu system.net system.pgpgio
netdata-influx
```

**Run from systemd unit file:**

Create this on your user `~/.config/systemd/user/netdata-influx.service`
```ini
[Unit]
Description=Netdata to InfluxDB exporter

[Service]
Type=simple
ExecStart=/usr/local/bin/netdata-influx
Environment=NI_INFLUX_ADDR=http://influxdb:8086
Environment=NI_INFLUX_DB=netdata
Environment=NI_NETDATA_API=https://netdata:19999/api
Environment=NI_HOST_TAG=localhost-main
Environment=NI_CHARTS=system.cpu system.net system.pgpgio

[Install]
WantedBy=multi-user.target
```

Then, you can start it and enable on boot:
```shell script
systemctl --user enable netdata-influx
systemctl --user start netdata-influx
```

**Comment by riptl** [comment]
@OUZYcn By the way, you can also just configure Netdata to write to InfluxDB directly via OpenTSDB protocol. You don't need to use this :) 

https://computingforgeeks.com/monitor-linux-server-with-netdata-and-grafana/

**Comment by MaurUppi** [comment]
Thank you so much. let me try to do it accordingly.

**Comment by riptl** [comment]
Closing this as it's been a while. Please re-open if you have any questions.
